### PR TITLE
added support for rx-java-2

### PR DESCRIPTION
**Pull request by SergiyKorotun**
added support for rx-java-2 Flowable

### CODE REVIEW

**Comment by SergiyKorotun** [comment]
@vicpinm If my changes will be OK.  Can we separate the library on two part like this? :
- 'com.github.vicpinm:krealmextensions-rxjava1:1.0.8'
- 'com.github.vicpinm:krealmextensions-rxjava2:1.0.8'
That allow us to reduce the number of dependencies of the library

**Comment by vicpinm** [comment]
Thanks for your contribution. I will review your commit in a few days, as soon as I can.  Thanks you very much.

**Comment by vicpinm** [comment]
@SergiyKorotun I've been reviewing your pull request carefully. I think you have done a great job. I have found some copy-paste mistakes in single test methods, and I have fixed them. I will upload a new version soon to maven, I hope to be able to do it in a few hours. Thanks you so much.

**Comment by papiyatoma** [comment]
Papiya

**Pull request merged**
