### PR TITLE
Configuration per model

### PR DESCRIPTION
**Pull request by magillus**

### CODE REVIEW

**Comment by magillus** [comment]
I had some errors on running the library-rx/library-rx2  instrumentation tests, but those also happens on master

**Comment by vicpinm** [comment]
Thanks a lot @magillus, I will execute all the tests and if everithing is ok, I will merge it with master.

**Comment by vicpinm** [comment]
Hi @magillus, I would like to make a small change in your PR. In my case, most of the time I only have one configuration for all my models, the default one. If I want to keep this behaviour with your changes, I would need to specify, model by model, the default configuration: 

    RealmConfigStore.Companion.init(Model1.class, defaultConfig);
    RealmConfigStore.Companion.init(Model2.class, defaultConfig);
    RealmConfigStore.Companion.init(Model3.class, defaultConfig);
    ...

If I didn't do that, each model would have a different configuration, as far I can see in this function:

    fun <T : RealmObject> fetchConfiguration(modelClass: Class<T>): RealmConfiguration {
          return configMap[modelClass] ?: RealmConfiguration.Builder().build()
    }

If you agree, I will change that function to return the default configuration, instead of creating one brand new configuration for every model not specified with the init function. It also have the advantage that we keep retrocompatibility with the previous version, so that you will get the same behaviour after updating the library.

**Comment by magillus** [comment]
I agree with you, I did missed that use case, please update it.

Also on back of my head I have a use of RealmModule so any classes in the module would use single configuration initialization - I will put issue about that.

**Comment by vicpinm** [comment]
@magillus I have finished with the changes, I'm going to test it with some projects, and in a few days I will merge it into master.

**Comment by vicpinm** [comment]
Hi @magillus, I have merged the PR after some refactor and bug fixes into master. I'm going to publish a beta in maven with this version today. Thanks you very much.

**Comment by magillus** [comment]
Thank you too..

**Pull request merged**
