### PR TITLE
Prevent the UI from freezing

### PR DESCRIPTION
**Pull request by markus2610**
I show an indeterminate progress bar to load and with the previous solution the animation remain stand until the data was finished fetched.

### CODE REVIEW

**Comment by vicpinm** [comment]
Hi, I'll check your commit as soon as I can, thanks you very much.

**Comment by vicpinm** [comment]
Hi markus, your commit is great, thanks you very much. I'd like to add something. In the rest of the queries of this lib, results are returned on the same thread the query was performed. I find odd that you perform a query on the main thread and results are returned on a background thread. I think user has the responsability to perform queries on the background thread, and if for some reason, he wants to perform it on the main thread, the result must be retourned on that thread. Observable queries are a special case, of course, because they require to be executed on a thread with a looper.  My point is that if a user executes an observable query on the main thread, I would keep that thread for executing that query. In other case, I would perform that query on a background thread, as you did in your commit. So I would do something like this:

     var backgroundThread : HandlerThread? = null
     var looper : Looper?

     if(Looper.myLooper() == null || Looper.myLooper() != Looper.getMainLooper()) {
        backgroundThread = BackgroundThread()
        backgroundThread.start()
        looper = backgroundThread.looper
     }
     else{
        looper = Looper.getMainLooper()
     }

I think you should also finish that background thread in doOnUnsubscribe method, something like:

    .doOnUnsubscribe ({
        realm?.close()
        subscription?.unsubscribe()
        backgroundThread?.interrupt()
     })

What do you think?

**Comment by markus2610** [comment]
Yes, the idea is good. It must be in a Observable.defer, otherwise you call the method always on the main thread.

`return Observable.defer {
 .....

  if (Looper.myLooper() == null || Looper.myLooper() != Looper.getMainLooper()) {
    backgroundThread = BackgroundThread()
    backgroundThread.start()
    looper = backgroundThread.looper
  } else {
    looper = Looper.getMainLooper()
  }

.....
}`

**Comment by vicpinm** [comment]
I have uploaded 1.0.6 version, which includes this changes.

**Pull request merged**
